apiVersion: v1
kind: ServiceAccount
metadata:
  name: kiali
  namespace: monitoring
  labels:
    app: kiali
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: monitoring
  labels:
    app: kiali
data:
  config.yaml: |
    auth:
      strategy: anonymous
    deployment:
      accessible_namespaces: ['**']
    server:
      port: 20001
      web_root: /kiali
    external_services:
      prometheus:
        url: http://prometheus:9090
      grafana:
        url: http://grafana:3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiali
  namespace: monitoring
  labels:
    app: kiali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kiali
  template:
    metadata:
      labels:
        app: kiali
    spec:
      serviceAccountName: kiali
      containers:
      - name: kiali
        image: quay.io/kiali/kiali:v1.75
        ports:
        - containerPort: 20001
        env:
        - name: PROMETHEUS_SERVICE_URL
          value: http://prometheus:9090
        - name: GRAFANA_SERVICE_URL
          value: http://grafana:3000
        volumeMounts:
        - name: kiali-configuration
          mountPath: /kiali-configuration
        - name: kiali-cert
          mountPath: /kiali-cert
      volumes:
      - name: kiali-configuration
        configMap:
          name: kiali
      - name: kiali-cert
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kiali
  namespace: monitoring
  labels:
    app: kiali
spec:
  ports:
  - name: http
    port: 20001
  selector:
    app: kiali
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kiali
  labels:
    app: kiali
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - endpoints
      - namespaces
      - nodes
      - pods
      - services
      - replicationcontrollers
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["extensions", "apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["networking.istio.io"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["security.istio.io"]
    resources: ["*"]
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kiali
  labels:
    app: kiali
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kiali
subjects:
  - kind: ServiceAccount
    name: kiali
    namespace: monitoring
