FROM node:18-alpine

WORKDIR /app/server

# Install dependencies only when needed
COPY package.json ./
COPY tsconfig.json ./

# Install dependencies and nodemon globally
RUN npm install
RUN npm install -g nodemon

# Set the correct permissions
RUN mkdir -p node_modules
RUN chown -R node:node .

# Switch to non-root user
USER node

# Copy source code
COPY --chown=node:node src/ ./src/

EXPOSE 3457
ENV PORT=3457

CMD ["npm", "run", "dev"]