version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    ports:
      - "3456:3456"
    environment:
      - VITE_API_URL=http://localhost:3457
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "3457:3457"
    environment:
      - NODE_ENV=development
      - BACKEND_PORT=3457
      - MONGODB_URI=mongodb://mongodb:27017/coworker-platform
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/coworker
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=30d
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - BASE_URL=http://localhost:3457
      - FRONTEND_URL=http://localhost:3456
      - CLIENT_URL=http://localhost:3456
      - CORS_ORIGINS=http://localhost:3456
    volumes:
      - ./server/src:/app/server/src
      - ./server/logs:/app/server/logs
    networks:
      - app-network
    depends_on:
      mongodb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    restart: unless-stopped

  task-service:
    build:
      context: ./backend
      dockerfile: packages/task-service/Dockerfile.dev
    ports:
      - "3455:3455"
    environment:
      - NODE_ENV=development
      - PORT=3455
      - KAFKA_BROKERS=kafka:9092
      - POSTGRES_URL=postgres://postgres:postgres@postgres:5432/coworker
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    volumes:
      - ./backend/packages/task-service/src:/app/backend/packages/task-service/src
      - ./backend/packages/shared-kernel/src:/app/backend/packages/shared-kernel/src
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coworker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  postgres_data:
