FROM node:18-alpine

WORKDIR /app

# Install dependencies only when needed
COPY package*.json ./
COPY tsconfig*.json ./
COPY vite.config.ts ./

# Install dependencies
RUN npm install

# Set the correct permissions
RUN mkdir -p node_modules
RUN chown -R node:node .

# Switch to non-root user
USER node

# Copy source code
COPY --chown=node:node . .

EXPOSE 3456
ENV PORT=3456

CMD ["npm", "run", "dev", "--", "--host", "--port", "3456"]