export enum AgentCapability {
  CODE_GENERATION = 'CODE_GENERATION',
  CODE_REVIEW = 'CODE_REVIEW',
  TESTING = 'TESTING',
  DEBUGGING = 'DEBUGGING',
  DOCUMENTATION = 'DOCUMENTATION',
  OPTIMIZATION = 'OPTIMIZATION',
  SECURITY_ANALYSIS = 'SECURITY_ANALYSIS',
  KNOWLEDGE_SHARING = 'KNOWLEDGE_SHARING'
}
