export enum AgentEventType {
  CREATED = 'AGENT.CREATED',
  UPDATED = 'AGENT.UPDATED',
  DELETED = 'AGENT.DELETED',
  STATUS_CHANGED = 'AGENT.STATUS_CHANGED',
  ERROR = 'AGENT.ERROR',
  TASK_ASSIGNED = 'AGENT.TASK_ASSIGNED',
  TASK_COMPLETED = 'AGENT.TASK_COMPLETED',
  TASK_FAILED = 'AGENT.TASK_FAILED',
  KNOWLEDGE_UPDATED = 'AGENT.KNOWLEDGE_UPDATED',
  COLLABORATION_STARTED = 'AGENT.COLLABORATION_STARTED',
  COLLABORATION_ENDED = 'AGENT.COLLABORATION_ENDED',
}
