export enum AgentStatus {
  ACTIVE = 'ACTIVE',
  BUSY = 'BUSY',
  DISCONNECTED = 'DISCONNECTED',
  ERROR = 'ERROR',
  IDLE = 'IDLE',
  INITIALIZING = 'INITIALIZING',
  OFFLINE = 'OFFLINE',
  PAUSED = 'PAUSED',
  SHUTTING_DOWN = 'SHUTTING_DOWN',
  TERMINATED = 'TERMINATED',
}
