FROM node:18-alpine

WORKDIR /app/backend/services/identity-service

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose the port the app runs on
EXPOSE 3458

# Command to run the application in development mode
CMD ["npm", "run", "dev"]
